apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2023-11-13T17:16:47Z"
    generation: 1
    labels:
      app: order
    name: order
    namespace: default
    resourceVersion: "31059"
    uid: c8a33cc5-d8e4-4d6e-9161-e4dabb0261f4
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: order
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: order
      spec:
        containers:
        - image: sinchangarai/order-image:1.0
          imagePullPolicy: IfNotPresent
          name: order-image
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2023-11-13T17:16:50Z"
      lastUpdateTime: "2023-11-13T17:16:50Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2023-11-13T17:16:47Z"
      lastUpdateTime: "2023-11-13T17:16:50Z"
      message: ReplicaSet "order-86747b8799" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cloud.google.com/neg: '{"ingress":true}'
    creationTimestamp: "2023-11-13T17:17:37Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    labels:
      app: order
    name: order
    namespace: default
    resourceVersion: "31652"
    uid: cfe1c224-fdab-49a0-bbf6-394599c9e31b
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.16.2.206
    clusterIPs:
    - 10.16.2.206
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 31419
      port: 8002
      protocol: TCP
      targetPort: 8002
    selector:
      app: order
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 104.197.114.155
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
